["```py\n#@title Step 9: Interacting with GPT-2\ninteract_model('345M',None,1,1,300,1,0,'/content/gpt-2/models') \n```", "```py\nHuman reason, in one sphere of its cognition, is called upon to\nconsider questions, which it cannot decline, as they are presented by\nits own nature, but which it cannot answer, as they transcend every\nfaculty of the mind. \n```", "```py\n\"We may grant to this conception the peculiarity that it is the only causal logic. \nIn the second law of logic as in the third, experience is measured at its end: apprehension is afterwards closed in consciousness.\nThe solution of scholastic perplexities, whether moral or religious, is not only impossible, but your own existence is blasphemous.\" \n```", "```py\n#@title Step 12: Interactive Context and Completion Examples\nimport os # import after runtime is restarted\nos.chdir(\"/content/gpt-2/src\")\n!python interactive_conditional_samples.py --temperature 0.8 --top_k 40 --model_name '117M' \n```", "```py\nHuman reason, in one sphere of its cognition, is called upon to\nconsider questions, which it cannot decline, as they are presented by\nits own nature, but which it cannot answer, as they transcend every\nfaculty of the mind. \n```", "```py\n\"Now, what is the nature of the reason, except that it is of a kind and power of mind that is so called on to think, and to understand?\nThe reason is the thing which apprehends, and seeks to understand, the objects of its minds, which apprehend and apprehend the things of itself. No one can speak of this reason without the understanding and the understanding of the human reason. But that knowledge and understanding which is the most natural of all the faculties, which, because it is understood by the human reason, is the most natural of all the faculties, is not without reason, but only without understanding. The human reason, who sees and knows the things which the natural sense, which, though in the natural sense, does not understand, is the source of every other knowledge which we understand. The reason is the thing which does not understand, but understands the things which we comprehend, and therefore, is not to be understood. I mean that the reason is the thing which does not understand, but knows only the things which we do understandâ€¦.\" \n```", "```py\ntry:\n  import openai\nexcept:\n  !pip install openai\n  import openai \n```", "```py\nopenai.api_key=[YOUR API KEY] \n```", "```py\nimport os\nimport openai\nos.environ['OPENAI_API_KEY'] ='[YOUR_KEY or KEY variable]'\nprint(os.getenv('OPENAI_API_KEY'))\nopenai.api_key = os.getenv(\"OPENAI_API_KEY\") \n```", "```py\nresponse = openai.Completion.create(\n engine=\"davinci\",\n prompt=\"Original: She no went to the market.\\nStandard American English:\",\n  temperature=0,\n  max_tokens=60,\n  top_p=1.0,\n  frequency_penalty=0.0,\n  presence_penalty=0.0,\n  stop=[\"\\n\"]\n) \n```", "```py\n#displaying the response object\nprint(response) \n```", "```py\n{\n  \"choices\": [\n    {\n      \"finish_reason\": \"stop\",\n      \"index\": 0,\n      \"logprobs\": null,\n      \"text\": \" She didn't go to the market.\"\n    }\n  ],\n  \"created\": 1639424815,\n  \"id\": \"cmpl-4ElZfXLl9jGRNQoojWRRGof8AKr4y\",\n  \"model\": \"davinci:2020-05-03\",\n  \"object\": \"text_completion\"} \n```", "```py\n#displaying the response object\nr = (response[\"choices\"][0])\nprint(r[\"text\"]) \n```", "```py\nShe didn't go to the market. \n```", "```py\n#Step 6: Running an NLP task with custom parameters\nresponse = openai.Completion.create(\n  #defult engine: davinci\n  engine=\"davinci\",\n  #default prompt for task:\"Original\"\n  prompt=\"Original: She no went to the market.\\n Standard American English:\",\n  temperature=0, \n  max_tokens=60,\n  top_p=1.0,\n  frequency_penalty=0.0,\n  presence_penalty=0.0,\n  stop=[\"\\n\"]\n) \n```", "```py\n`prompt=\"Original: She no went to the market.\\n Standard American English:\"` \n```", "```py\n`Human reason, in one sphere of its cognition, is called upon to consider questions, which it cannot decline, as they are presented by its own nature, but which it cannot answer, as they transcend every faculty of the mind.` \n`GPT-3's response:`\n`What is meant by this is that there are some things in our experience that are beyond reason. It is not that reason is a bad guide or is insufficient, but that there are some things that are beyond its reach. An example of this would be the existence of God.` \n```", "```py\ntry:\n  import openai\nexcept:\n  !pip install openai\n  import openai \n```", "```py\nimport openai \n```", "```py\ntry:\n  import wandb\nexcept:\n  !pip install wandb\n  import wandb \n```", "```py\nopenai.api_key=\"[YOUR_KEY]\" \n```", "```py\nBased on the analysis we will perform the following actions:\n- [Necessary] Your format 'CSV' will be converted to 'JSONL'\n- [Necessary] Remove 27750 rows with empty completions\n- [Recommended] Remove 903 duplicate rows [Y/n]: y\n- [Recommended] Add a suffix separator ' ->' to all prompts [Y/n]: y\n- [Recommended] Remove prefix 'completion:' from all completions [Y/n]: y\n- [Recommended] Add a suffix ending '\\n' to all completions [Y/n]: y\n- [Recommended] Add a whitespace character to the beginning of the completion [Y/n]: y \n```", "```py\nimport openai\nimport os\nos.environ['OPENAI_API_KEY'] =[YOUR_KEY]\nprint(os.getenv('OPENAI_API_KEY')) \n```", "```py\n!openai api fine_tunes.create -t \"kantgpt_prepared.jsonl\" -m \"ada\" \n```", "```py\n!openai api fine_tunes.follow -i [YOUR_FINE_TUNE] \n```", "```py\n!openai api completions.create -m ada:[YOUR_MODEL INFO] \"Several concepts are a priori such as\" \n```", "```py\nSeveral concepts are a priori such as the term  freedom and the concept of _free will_.substance \n```"]